<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.0.42</Version>
    <AssemblyName>VieriNexus</AssemblyName>
    <RootNamespace>VieriNexus</RootNamespace>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VieriNexus.Domain\VieriNexus.Domain.csproj" />
    <ProjectReference Include="..\VieriNexus.Contracts\VieriNexus.Contracts.csproj" />
    <ProjectReference Include="..\VieriNexus.Application\VieriNexus.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\VieriNexusLogo.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
