<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.5.3.2</Version>
    <AssemblyName>VieriLink</AssemblyName>
    <RootNamespace>VieriLink</RootNamespace>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="VieriLink.Tests\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.0" />
  </ItemGroup>
</Project>
