name: Debug Build and Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        dalamud:
          - name: Latest
            url: https://goatcorp.github.io/dalamud-distrib/latest.zip
          - name: Staging
            url: https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
    name: Build against ${{ matrix.dalamud.name }} Dalamud
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Initialize PunishLib
        run: git submodule update --init --recursive PunishLib

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x.x

      - name: Download Dalamud
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "$env:AppData\XIVLauncher\addon\Hooks\dev" -Force | Out-Null
          Invoke-WebRequest -Uri "${{ matrix.dalamud.url }}" -OutFile dalamud.zip
          Expand-Archive -Path dalamud.zip -DestinationPath "$env:AppData\XIVLauncher\addon\Hooks\dev" -Force

      - name: Build Debug
        run: dotnet build Avarice/Avarice.csproj --configuration Debug

      - name: Build Release
        run: dotnet build Avarice/Avarice.csproj --configuration Release
